name: pixeltasks
description: Gerencie seus projetos individuais de forma simples.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: any
  mobx: ^1.2.0
  flutter_mobx: ^1.1.0
  google_fonts: ^1.1.0
  path_provider: ^1.6.8
  flutter_icons: ^1.1.0
  flutter_bcrypt: ^1.0.5
  get: ^2.5.10
  flushbar: ^1.10.4

dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  flutter_test:
    sdk: flutter
  
flutter:

  uses-material-design: true
